# Site settings
title:          Sanghyuk Kim
description:    "Ph.D. Student at KAIST"
url:            "https://kim-sanghyuk.github.io/"
baseurl: ""

# Google Analytics
google_analytics: G-Y3PMVVHXSX

# Author
author:
  name:         Sanghyuk Kim
  url:          https://kim-sanghyuk.github.io/
  email:        sanghyukkim@kaist.ac.kr

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

theme: minima

# Gems
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
paginate_path: "/page:num/"

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _site
  - .jekyll-cache
  - tale.gemspec
  
# Disqus (Set to your disqus id)
disqus:         jekyll-tale
